inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.7.2
  DisplayCopNames: true
  SuggestExtensions: false
  NewCops: enable
  Include:
    - app/**/*
    - lib/**/*.rb
  Exclude:
    - app/assets/**/*
    - app/views/**/*
    - bin/**/*
    - config/**/*
    - db/**/*
    - lib/tasks/**/*
    - spec/**/*
    - test/**/*

Lint/EmptyFile:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Layout/LineLength:
  Max: 100

Metrics/ParameterLists:
  Enabled: false

Naming/FileName:
  Exclude:
    - Gemfile
    - Capfile
    - Rakefile

Style/Documentation:
  Enabled: false

Style/Lambda:
  EnforcedStyle: literal
