version: "3.9"
services:
  web:
    build:
      context: .
      target: rails_webserver
      args:
        DATABASE_URL: ${DATABASE_URL:?Missing database url}
        RAILS_ENV: ${RAILS_ENV:-production}
        RAILS_LOG_TO_STDOUT: ${RAILS_LOG_TO_STDOUT-enabled}
        RAILS_MASTER_KEY: ${RAILS_MASTER_KEY:?Missing master key}
        REDIS_URL: ${REDIS_URL:?Missing redis url}
    ports:
      - ${PORT:-4000}:3000
  sidekiq:
    build:
      context: .
      target: sidekiq_process
      args:
        DATABASE_URL: ${DATABASE_URL?:Missing database url}
        RAILS_ENV: ${RAILS_ENV:-production}
        RAILS_LOG_TO_STDOUT: ${RAILS_LOG_TO_STDOUT-enabled}
        RAILS_MASTER_KEY: ${RAILS_MASTER_KEY:?Missing master key}
        REDIS_URL: ${REDIS_URL:?Missing redis url}
