# TODO: change database names to application name

development: &default
  adapter: mysql2
  database: app_development

test:
  <<: *default
  database: app_test

staging:
  <<: *default
  database: app_staging

production:
  <<: *default
  database: app_production
